micronaut:
  application:
    name: pixKeymanagerGrpc

api:
  itau:
    url: ${API_ITAU_URL_BASE:`http://localhost:9091`}

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: adriano
    password: 'adriano'
    schema-generate: CREATE_DROP
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl.auto: create-drop
        show_sql: true
        generate_ddl: true
        format_sql: true